In [1]:
%config InlineBackend.figure_format = 'retina'

import numpy as np

from hmr import Reloader
import heatgraphy as hg

hg = Reloader(hg)

In [2]:
10 * 11

110

In [3]:
matrix = np.arange(0, 110, 1).reshape(10, 11)
matrix

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [4]:
dm = hg.Deformation(matrix)
dm.set_split_col([3, 7])
dm.cluster_col()
dm.transform_col(np.arange(0, 22, 1).reshape(2, 11))

[array([[ 0,  1,  2],
       [11, 12, 13]]), array([[ 3,  4,  5,  6],
       [14, 15, 16, 17]]), array([[ 7,  8,  9, 10],
       [18, 19, 20, 21]])]


[array([[ 0,  1,  2],
        [11, 12, 13]]),
 array([[ 3,  4,  5,  6],
        [14, 15, 16, 17]]),
 array([[ 7,  8,  9, 10],
        [18, 19, 20, 21]])]

In [15]:
dm = hg.Deformation(matrix)
dm.set_split_col([5])
dm.cluster_row()
dm.transform(matrix)

split by col


[array([[  0,   1,   2,   3,   4],
        [ 11,  12,  13,  14,  15],
        [ 22,  23,  24,  25,  26],
        [ 33,  34,  35,  36,  37],
        [ 44,  45,  46,  47,  48],
        [ 55,  56,  57,  58,  59],
        [ 66,  67,  68,  69,  70],
        [ 77,  78,  79,  80,  81],
        [ 88,  89,  90,  91,  92],
        [ 99, 100, 101, 102, 103]]),
 array([[  5,   6,   7,   8,   9,  10],
        [ 16,  17,  18,  19,  20,  21],
        [ 27,  28,  29,  30,  31,  32],
        [ 38,  39,  40,  41,  42,  43],
        [ 49,  50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64,  65],
        [ 71,  72,  73,  74,  75,  76],
        [ 82,  83,  84,  85,  86,  87],
        [ 93,  94,  95,  96,  97,  98],
        [104, 105, 106, 107, 108, 109]])]

In [9]:
dm = hg.Deformation(matrix)
dm.set_split_row([3, 7])
dm.set_split_col([3, 7])
dm.cluster_row()
dm.cluster_col()
dm.transform(matrix)

[[array([[ 0,  1,  2],
         [11, 12, 13],
         [22, 23, 24]]),
  array([[ 3,  4,  5,  6],
         [14, 15, 16, 17],
         [25, 26, 27, 28]]),
  array([[ 7,  8,  9, 10],
         [18, 19, 20, 21],
         [29, 30, 31, 32]])],
 [array([[33, 34, 35],
         [44, 45, 46],
         [55, 56, 57],
         [66, 67, 68]]),
  array([[36, 37, 38, 39],
         [47, 48, 49, 50],
         [58, 59, 60, 61],
         [69, 70, 71, 72]]),
  array([[40, 41, 42, 43],
         [51, 52, 53, 54],
         [62, 63, 64, 65],
         [73, 74, 75, 76]])],
 [array([[ 77,  78,  79],
         [ 88,  89,  90],
         [ 99, 100, 101]]),
  array([[ 80,  81,  82,  83],
         [ 91,  92,  93,  94],
         [102, 103, 104, 105]]),
  array([[ 84,  85,  86,  87],
         [ 95,  96,  97,  98],
         [106, 107, 108, 109]])]]